=== eznaljesok/event-radar/schema/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Event Radar event",
  "type": "object",
  "required": ["id", "kategorija", "naslov", "datum", "prizorisce", "kraj", "viri"],
  "properties": {
    "id": {
      "type": "string",
      "description": "sha1(naslov|datum|prizorisce)"
    },
    "kategorija": {
      "type": "string",
      "enum": ["glasba", "kultura", "sport"]
    },
    "naslov": { "type": "string", "minLength": 1 },
    "datum": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
      "description": "YYYY-MM-DD"
    },
    "ura": {
      "type": ["string", "null"],
      "pattern": "^[0-9]{2}:[0-9]{2}$",
      "description": "HH:MM ali null"
    },
    "prizorisce": { "type": "string" },
    "kraj": { "type": "string" },
    "viri": {
      "type": "array",
      "items": { "type": "string", "format": "uri" },
      "minItems": 1
    },
    "opis": {
      "type": "string",
      "description": "1-2 stavka: kaj / kje / kdaj / kdo (doda analyst)"
    },
    "odmevnost": {
      "type": "object",
      "required": ["skupaj", "doseg", "prepoznavnost", "obisk", "redkost", "medijski_signal"],
      "properties": {
        "skupaj": { "type": "integer", "minimum": 0, "maximum": 100 },
        "doseg": { "type": "integer", "minimum": 0, "maximum": 5 },
        "prepoznavnost": { "type": "integer", "minimum": 0, "maximum": 5 },
        "obisk": { "type": "integer", "minimum": 0, "maximum": 5 },
        "redkost": { "type": "integer", "minimum": 0, "maximum": 5 },
        "medijski_signal": { "type": "integer", "minimum": 0, "maximum": 5 }
      }
    },
    "znacke": {
      "type": "array",
      "items": { "type": "string" },
      "maxItems": 3
    }
  }
}

=== eznaljesok/event-radar/docs/events.json
[
  {
    "id": "6ae76655b8bb3647e11e1234185625bf88e7239c",
    "kategorija": "glasba",
    "naslov": "Hamo & Tribute 2 Love - 20 years",
    "datum": "2026-09-12",
    "ura": "20:00",
    "prizorisce": "Kino Šiška",
    "kraj": "Ljubljana",
    "viri": [
      "https://www.kinosiska.si/en/dogodek/"
    ],
    "opis": "Koncert zasedbe Hamo & Tribute 2 Love ob 20. obletnici delovanja v Kino Šiški v Ljubljani, 12. septembra 2026 ob 20.00.",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 3,
      "obisk": 2,
      "redkost": 2,
      "medijski_signal": 1,
      "skupaj": 43
    },
    "znacke": ["jubilejni koncert"]
  },
  {
    "id": "a0622131ed5171a379d7dced9c5bacba67c512e0",
    "kategorija": "glasba",
    "naslov": "POPPY BY CVETLIČARNA",
    "datum": "2026-09-12",
    "ura": "22:00",
    "prizorisce": "Cvetličarna",
    "kraj": "Ljubljana",
    "viri": [
      "https://www.entrio.si/en/venue/ljubljana/cvetlicarna",
      "https://www.eventim.si/city/ljubljana-5738/venue/klub-cvetlicarna-92438/"
    ],
    "opis": "Klubski glasbeni večer POPPY v klubu Cvetličarna v Ljubljani, 12. septembra 2026 ob 22.00.",
    "odmevnost": {
      "doseg": 1,
      "prepoznavnost": 1,
      "obisk": 2,
      "redkost": 1,
      "medijski_signal": 1,
      "skupaj": 24
    },
    "znacke": []
  },
  {
    "id": "c6491d46b0d4be9a5f119eab94208917a2a6b930",
    "kategorija": "glasba",
    "naslov": "Rekviem v belem - umirajoči ledeniki",
    "datum": "2026-09-12",
    "ura": "20:00",
    "prizorisce": "Kosovelova dvorana, Cankarjev dom",
    "kraj": "Ljubljana",
    "viri": [
      "https://vstopnice.cd-cc.si/en/all.html"
    ],
    "opis": "Tematski koncert o taljenju ledenikov z naslovom Rekviem v belem v Kosovelovi dvorani Cankarjevega doma v Ljubljani, 12. septembra 2026 ob 20.00.",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 2,
      "obisk": 2,
      "redkost": 3,
      "medijski_signal": 1,
      "skupaj": 41
    },
    "znacke": ["tematski koncert"]
  },
  {
    "id": "181cf2619bd1e34100626a37b38fe2e28042c2f2",
    "kategorija": "glasba",
    "naslov": "The Rumjacks",
    "datum": "2026-09-12",
    "ura": null,
    "prizorisce": "Orto Bar",
    "kraj": "Ljubljana",
    "viri": [
      "https://www.songkick.com/venues/2206978-orto-bar"
    ],
    "opis": "Koncert avstralske keltsko-punk zasedbe The Rumjacks v klubu Orto Bar v Ljubljani, 12. septembra 2026 (ura ni znana).",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 3,
      "obisk": 2,
      "redkost": 2,
      "medijski_signal": 1,
      "skupaj": 43
    },
    "znacke": ["mednarodni izvajalec", "neznano"]
  },
  {
    "id": "c7fa62135ae0dbd0b47a4f57f20a0b97dee6b440",
    "kategorija": "kultura",
    "naslov": "ARTish – umetniška tržnica",
    "datum": "2026-09-12",
    "ura": "10:00-17:00",
    "prizorisce": "Gallusovo nabrežje",
    "kraj": "Ljubljana",
    "viri": [
      "https://www.visitljubljana.com/sl/obiskovalci/prireditve"
    ],
    "opis": "Umetniška tržnica ARTish na Gallusovem nabrežju v Ljubljani, 12. septembra 2026 med 10. in 17. uro.",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 1,
      "obisk": 3,
      "redkost": 1,
      "medijski_signal": 1,
      "skupaj": 34
    },
    "znacke": ["brezplačno", "na prostem"]
  },
  {
    "id": "8ddb3b6f5d071e5af8b1f0a172e9bdae742f3522",
    "kategorija": "kultura",
    "naslov": "Gorenjski slavček (opera, A. Foerster)",
    "datum": "2026-09-12",
    "ura": "18:00",
    "prizorisce": "SNG Opera in balet Ljubljana",
    "kraj": "Ljubljana",
    "viri": [
      "https://opera.mojekarte.si/en/all.html"
    ],
    "opis": "Uprizoritev opere Gorenjski slavček Antona Foersterja v SNG Opera in balet Ljubljana, 12. septembra 2026 ob 18.00.",
    "odmevnost": {
      "doseg": 3,
      "prepoznavnost": 2,
      "obisk": 2,
      "redkost": 2,
      "medijski_signal": 1,
      "skupaj": 44
    },
    "znacke": ["opera"]
  },
  {
    "id": "e92199ed36707b3e85ab55be4df9eca4042f0562",
    "kategorija": "kultura",
    "naslov": "Iztok Kocen: Klik za ljubezen",
    "datum": "2026-09-12",
    "ura": "19:00",
    "prizorisce": "Cankarjev dom, Štihova dvorana",
    "kraj": "Ljubljana",
    "viri": [
      "https://www.cd-cc.si/en/monthly-events-calendar"
    ],
    "opis": "Uprizoritev operne komedije Iztok Kocen: Klik za ljubezen v Štihovi dvorani Cankarjevega doma v Ljubljani, 12. septembra 2026 ob 19.00.",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 3,
      "obisk": 3,
      "redkost": 1,
      "medijski_signal": 1,
      "skupaj": 44
    },
    "znacke": []
  },
  {
    "id": "ffed6264d4e7317931e55f31bf09cfc7c9d4e9f5",
    "kategorija": "kultura",
    "naslov": "Mala čarovnica (lutkovna predstava)",
    "datum": "2026-09-12",
    "ura": "11:00 in 17:00",
    "prizorisce": "Lutkovno gledališče Ljubljana",
    "kraj": "Ljubljana",
    "viri": [
      "https://www.lgl.si/si/predstave/vse-predstave"
    ],
    "opis": "Lutkovna predstava Mala čarovnica v Lutkovnem gledališču Ljubljana, 12. septembra 2026 ob 11.00 in 17.00.",
    "odmevnost": {
      "doseg": 1,
      "prepoznavnost": 1,
      "obisk": 2,
      "redkost": 1,
      "medijski_signal": 1,
      "skupaj": 24
    },
    "znacke": ["za otroke"]
  },
  {
    "id": "eaf199db23ebf6dbd98d4387940556e5d61fb9d0",
    "kategorija": "sport",
    "naslov": "NK Bravo : NK Celje (Prva liga Telemach, 9. krog)",
    "datum": "2026-09-12",
    "ura": "20:15",
    "prizorisce": "Stadion Stožice",
    "kraj": "Ljubljana",
    "viri": [
      "https://planetnogomet.si/novice/ticklio-9-26-27-bravo-celje-stozice/",
      "https://www.nzs.si/novica/Pred_tekmo_Bravo_-_Celje?id=62690&id_landing=&id_objekta=3",
      "https://www.sport-ljubljana.si/nk-bravo-nk-celje-prva-slovenska-nogometna-liga/"
    ],
    "opis": "Nogometna tekma 9. kroga Prve lige Telemach med NK Bravo in NK Celje na Stadionu Stožice v Ljubljani, 12. septembra 2026 ob 20.15.",
    "odmevnost": {
      "doseg": 3,
      "prepoznavnost": 3,
      "obisk": 3,
      "redkost": 1,
      "medijski_signal": 2,
      "skupaj": 52
    },
    "znacke": ["prva liga"]
  },
  {
    "id": "bb602567d02e4c5c9d66e7b7aab8bb9044f5f034",
    "kategorija": "sport",
    "naslov": "Nočni tek Ljubljanica 2026",
    "datum": "2026-09-12",
    "ura": "večer (ni natančnega podatka)",
    "prizorisce": "Stritarjeva ulica, center Ljubljane",
    "kraj": "Ljubljana",
    "viri": [
      "https://ljubljanica.net/program/",
      "https://ljubljanica.net/trail-ljubljana/",
      "https://trail-ljubljana.eu/en/home-2/",
      "https://www.24ur.com/novice/slovenija/sportni-vikend-ljubljanica-2026-bo-med-11-in-13-septembrom-v-sredisce-ljubljane-pripeljal-nocni-tek-trail-pohodnistvo-kolesarjenje-in-pestro-druzinsko-sportno-dogajanje.html",
      "https://ljubljanica.net/nocni-tek-ljubljanica/",
      "https://ljubljanica.net/bike-festival-ljubljana/"
    ],
    "opis": "Nočni tek v okviru Športnega vikenda Ljubljanica po centru Ljubljane, 12. septembra 2026 zvečer (natančna ura ni znana).",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 1,
      "obisk": 3,
      "redkost": 2,
      "medijski_signal": 2,
      "skupaj": 39
    },
    "znacke": ["neznano"]
  },
  {
    "id": "381ac1e3427e0b1d3e9fc34b5100fddadeca06a0",
    "kategorija": "glasba",
    "naslov": "Global Kryner",
    "datum": "2026-09-13",
    "ura": "20:00",
    "prizorisce": "Linhartova dvorana, Cankarjev dom",
    "kraj": "Ljubljana",
    "viri": [
      "https://vstopnice.cd-cc.si/en/all.html",
      "https://www.cd-cc.si/en/monthly-events-calendar"
    ],
    "opis": "Koncert avstrijsko-švicarske zasedbe Global Kryner v Linhartovi dvorani Cankarjevega doma v Ljubljani, 13. septembra 2026 ob 20.00.",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 2,
      "obisk": 2,
      "redkost": 2,
      "medijski_signal": 1,
      "skupaj": 38
    },
    "znacke": ["mednarodni izvajalec"]
  },
  {
    "id": "df381a9e1b2643553c8d53acb51ddd05053ef426",
    "kategorija": "glasba",
    "naslov": "Iztok Kocen: Klik za Ljubezen - operna komedija",
    "datum": "2026-09-13",
    "ura": "19:30",
    "prizorisce": "Štihova dvorana, Cankarjev dom",
    "kraj": "Ljubljana",
    "viri": [
      "https://vstopnice.cd-cc.si/en/all.html",
      "https://www.cd-cc.si/en/monthly-events-calendar"
    ],
    "opis": "Ponovitev operne komedije Iztok Kocen: Klik za ljubezen v Štihovi dvorani Cankarjevega doma v Ljubljani, 13. septembra 2026 ob 19.30.",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 3,
      "obisk": 3,
      "redkost": 1,
      "medijski_signal": 1,
      "skupaj": 44
    },
    "znacke": []
  },
  {
    "id": "ba58f2c721e36e47bc07958bd3fa569a9e663b5f",
    "kategorija": "sport",
    "naslov": "Otroški teki Povodnega moža (Športni vikend Ljubljanica)",
    "datum": "2026-09-13",
    "ura": "ni natančnega podatka",
    "prizorisce": "center Ljubljane",
    "kraj": "Ljubljana",
    "viri": [
      "https://ljubljanica.net/otroski-teki-povodnega-moza/",
      "https://ljubljanica.net/program/"
    ],
    "opis": "Otroški teki Povodnega moža v okviru Športnega vikenda Ljubljanica v centru Ljubljane, 13. septembra 2026 (ura ni znana).",
    "odmevnost": {
      "doseg": 1,
      "prepoznavnost": 1,
      "obisk": 2,
      "redkost": 1,
      "medijski_signal": 1,
      "skupaj": 24
    },
    "znacke": ["za otroke", "neznano"]
  },
  {
    "id": "e8a043e47f78694b7aaf8ebabca62c3fba1f2d8b",
    "kategorija": "sport",
    "naslov": "Skupinski tek NLB Ljubljanskega maratona",
    "datum": "2026-09-13",
    "ura": "ni natančnega podatka",
    "prizorisce": "Ljubljana",
    "kraj": "Ljubljana",
    "viri": [
      "https://www.timingljubljana.si/Koledar.aspx",
      "https://ljubljanskimaraton.si/"
    ],
    "opis": "Skupinski trening tek v organizaciji NLB Ljubljanskega maratona po Ljubljani, 13. septembra 2026 (ura ni znana).",
    "odmevnost": {
      "doseg": 2,
      "prepoznavnost": 2,
